# jekyll serve --baseurl "" --watch
name: External Prototype
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, .gitignore, README.md, COPYING, build.sh]
# domain: http://malmostad.github.io
domain: http://webapps07.malmo.se
baseurl: /juni2014
# baseurl: /external-prototype
# cdn_url: //assets.malmo.se/external/v4-staging
cdn_url: //www.local.malmo.se:3001/assets
permalink: /:categories/:title
relative_permalinks: false
sass:
  style: :compressed
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: rsquo,rsquo,rdquo,rdquo
  use_coderay: false
